export { default as AboutMe } from './AboutMe/AboutMe'
export { default as ContactMe } from './ContactMe/ContactMe'
export { default as Home } from './Home/Home'
export { default as Cursor } from './Cursor/Cursor'
export { default as Navbar } from './Navbar/Navbar'
export { default as Services } from './Services/Services'
export { default as Projects } from './Projects/Projects'
// export { default as ScrollBar } from './ScrollBar/ScrollBar'
