# This is a basic workflow to help you get started with Actions

name: Deploy react app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Install React Router
        run: yarn add history@5 react-router-dom@^6.0.0-beta.0

      - name: Install Craco
        run: yarn add craco

      - name: Build React App
        run: yarn build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./build portfolio-aezaz-ali-1997-react-app.surge.sh --token ${{secrets.SURGE_TOKEN}}
